plugins:
  - jekyll-seo-tag

social:
  name: Machines Don't Get The Jokes
  links:
    - https://www.facebook.com/*link*
    - http://instagram.com/*link*

logo: /icon-512.png
url: https://URL.HERE

title: "*TITLE*"
lang: "en_US"

defaults:
  -
    scope:
      path: ""
    values:
      image: /icon-512.png
